force-app/src/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <description>Object to manage booked loans</description>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/src/objects/Loan_Charge__c/Loan_Charge__c.object-meta.xml
<CustomObject>
    <label>Loan Charge</label>
    <nameField>
        <displayFormat>LC-{00000}</displayFormat>
        <label>Loan Charge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/src/objects/Loan_Charge__c/fields/Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>Charge_Type__c</fullName>
    <label>Charge Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Release Charge</fullName>
            </value>
            <value>
                <fullName>Interest Charge</fullName>
            </value>
            <value>
                <fullName>Legal Fee</fullName>
            </value>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/src/objects/Loan_Charge__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Loan Charges</relationshipLabel>
    <relationshipName>Loan_Charges</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/src/classes/LoanChargeTriggerHandler.cls
public inherited sharing class LoanChargeTriggerHandler extends ATriggerHandler {
	@TestVisible
	private static Boolean performDMLOverride;

	public override void run(
		final List<SObject> newList,
		final Map<Id, SObject> newMap,
		final List<SObject> oldList,
		final Map<Id, SObject> oldMap
	) {
		List<Loan_Charge__c> newRecords = (List<Loan_Charge__c>) newList;
		Map<Id, Loan_Charge__c> newRecordsMap = (Map<Id, Loan_Charge__c>) newMap;

		if (this.isBefore) {
			if (this.isInsert) {
				this.validateUniqueReleaseCharge(newRecords);
			}

			if (this.isUpdate) {
				this.validateUniqueReleaseCharge(newRecords);
			}
		}

		if (this.shouldRun()) {
			/**
			 * Perform DML
			 */
		}
	}

	protected override Boolean shouldRun() {
		if (performDMLOverride != null) {
			return performDMLOverride;
		}
		return true;
	}

	private void validateUniqueReleaseCharge(
		final List<Loan_Charge__c> records
	) {
		final Map<Id, List<Loan_Charge__c>> loanIdToRecordMap = getLoanIdToChargeMap(
			records
		);

		List<Loan_Charge__c> existingCharges = [
			SELECT Id, Loan__c
			FROM Loan_Charge__c
			WHERE
				Loan__c IN :loanIdToRecordMap.keySet()
				AND Charge_Type__c = 'Release Charge'
		];

		for (Loan_Charge__c existingCharge : existingCharges) {
			List<Loan_Charge__c> newCharges = loanIdToRecordMap.get(
				existingCharge.Loan__c
			);
			if (newCharges != null) {
				for (Loan_Charge__c newCharge : newCharges) {
					newCharge.addError(
						'Cannot be assoiated with multiple charges'
					);
				}
			}
		}
	}

	private Map<Id, List<Loan_Charge__c>> getLoanIdToChargeMap(
		final List<Loan_Charge__c> records
	) {
		final Map<Id, List<Loan_Charge__c>> loanIdToRecordMap = new Map<Id, List<Loan_Charge__c>>();
		for (Loan_Charge__c record : records) {
			final Id loanId = record.Loan__c;
			if (loanId != null) {
				if (loanIdToRecordMap.get(loanId) == null) {
					loanIdToRecordMap.put(loanId, new List<Loan_Charge__c>());
				}
				loanIdToRecordMap.get(loanId).add(record);
			}
		}
		return loanIdToRecordMap;
	}
}