force-app/src/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <description>Object to manage booked loans</description>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/src/objects/Loan__c/fields/Date_Loan_Issued__c.field-meta.xml
<CustomField>
    <fullName>Date_Loan_Issued__c</fullName>
    <description>The date when the loan was issued</description>
    <label>Loan Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/src/objects/Loan__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <description>Duration of the loan in months</description>
    <label>Loan Term (Months)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/src/objects/Loan_Charge__c/Loan_Charge__c.object-meta.xml
<CustomObject>
    <label>Loan Charge</label>
    <nameField>
        <displayFormat>LC-{00000}</displayFormat>
        <label>Loan Charge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/src/objects/Loan_Charge__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Charge amount</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/src/objects/Loan_Charge__c/fields/Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>Charge_Type__c</fullName>
    <label>Charge Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Release Charge</fullName>
            </value>
            <value>
                <fullName>Interest Charge</fullName>
            </value>
            <value>
                <fullName>Legal Fee</fullName>
            </value>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/src/objects/Loan_Charge__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>The date when the charge was applied.</description>
    <label>Charge Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/src/objects/Loan_Charge__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Loan Charges</relationshipLabel>
    <relationshipName>Loan_Charges</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/src/classes/LoanTriggerHandler.cls
public inherited sharing class LoanTriggerHandler extends ATriggerHandler {
	@TestVisible
	private static Boolean performDMLOverride;

	final private List<Loan_Charge__c> loanChargesToInsert = new List<Loan_Charge__c>();

	public override void run(
		final List<SObject> newList,
		final Map<Id, SObject> newMap,
		final List<SObject> oldList,
		final Map<Id, SObject> oldMap
	) {
		final List<Loan__c> newLoans = (List<Loan__c>) newList;
		if (this.isAfter) {
			if (this.isInsert) {
				for (Loan__c loan : newLoans) {
					loanChargesToInsert.add(createReleaseChargeRecord(loan));
				}
			}
		}

		if (this.shouldRun()) {
			if (loanChargesToInsert.size() > 0) {
				insert loanChargesToInsert;
			}
		}
	}

	protected override Boolean shouldRun() {
		if (performDMLOverride != null) {
			return performDMLOverride;
		}
		return true;
	}

	private static Loan_Charge__c createReleaseChargeRecord(
		final Loan__c loan
	) {
		return new Loan_Charge__c(
			Loan__c = loan.Id,
			Date__c = Date.valueOf(loan.Date_Loan_Issued__c)
				.addMonths(Integer.valueOf(loan.Term__c)),
			Charge_Type__c = 'Release Charge',
			Amount__c = 500.00
		);
	}
}