force-app/src/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <description>Object to manage booked loans</description>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/src/objects/Loan_Charge__c/Loan_Charge__c.object-meta.xml
<CustomObject>
    <label>Loan Charge</label>
    <nameField>
        <displayFormat>LC-{00000}</displayFormat>
        <label>Loan Charge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/src/objects/Loan_Charge__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Charge amount</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/src/objects/Loan_Charge__c/fields/Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>Charge_Type__c</fullName>
    <label>Charge Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Release Charge</fullName>
            </value>
            <value>
                <fullName>Interest Charge</fullName>
            </value>
            <value>
                <fullName>Legal Fee</fullName>
            </value>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/src/objects/Loan_Charge__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>The date when the charge was applied.</description>
    <label>Charge Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/src/objects/Loan_Charge__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Loan Charges</relationshipLabel>
    <relationshipName>Loan_Charges</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/src/classes/LoanTriggerHandlerTest.cls
@isTest(isParallel=true)
private class LoanTriggerHandlerTest {
	@isTest
	private static void shouldCreateLoanChargeOnInsert() {
		disableActiveTriggers();

		final Date currentDate = Date.today();
		final Loan__c loan = LoanFixtures.createLoan(null, currentDate);

		final LoanTriggerHandler handler;
		
		Test.startTest();
		handler = new LoanTriggerHandler();
		handler.setIsAfter(true);
		handler.setIsInsert(true);
		handler.run(new List<Loan__c>{ loan }, null, null, null);
		Test.stopTest();

		final Loan_Charge__c[] charges = handler.loanChargesToInsert;

		Assert.areEqual(charges.size(), 1, '1 loan charge should be created');

		Loan_Charge__c initialCharge = charges[0];
		Assert.areEqual(
			initialCharge.Date__c,
			currentDate.addMonths(36),
			'Loan issue date should be the date of issue advanced by the term'
		);
		Assert.areEqual(
			initialCharge.Charge_Type__c,
			'Release Charge',
			'Initial charge should be Release Charge'
		);
		Assert.areEqual(
			initialCharge.Amount__c,
			500.00,
			'Initial charge amount should be 500'
		);
	}

	public static void disableActiveTriggers() {
		LoanTriggerHandler.performDMLOverride = false;
	}
}